version: '3.2'
services:
  sonarqube:
    build:
      context: sonarqube/
    ports:
      - 9000:9000
      - 9092:9092
    container_name: sonarqube
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
